When compiling on gcc 10.3.0 WITH GLIBC 2.33 the following error can occur:
socket.h:24: multiple definition of `world_decl'

Since using an additional preprocessor guard would not work, I have made
world_decl 'extern' which allows compilation successfully.